const AI_CONTENT_NOTICE_FR =
  "Nota bene : Ce contenu a été généré par IA. Je suis en train de travailler sur cette page pour proposer un contenu personnel et d'une meilleure qualité.";

const AI_CONTENT_NOTICE_EN =
  'Note: This content was generated by AI. I am working on this page to provide personal content of better quality.';

export function isDesignPatternsArticle(slug: string[]): boolean {
  const path = slug.join('/');
  return path.startsWith('engineering/design-patterns') || path.startsWith('programming/design-patterns');
}

export function getAiContentNotice(locale: string): string {
  return locale === 'en' ? AI_CONTENT_NOTICE_EN : AI_CONTENT_NOTICE_FR;
}
